version: '3.6'

networks:
  web:
    external: true
  internal:
    external: false

services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ideciclo
      POSTGRES_USER: ideciclo
    image: 'postgres:12'
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  ideciclo_api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ideciclo.rule=Host(`api.ideciclo.ameciclo.org`)"
      - "traefik.http.routers.ideciclo.tls.certresolver=le"
      - "traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirectscheme.redirectscheme.permanent=true"
      - "traefik.docker.network=web"
    networks:
      - internal
      - web
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      PGUSER: ideciclo
      PGPASSWORD: ideciclo
      PGDATABASE: ideciclo
      PGPORT: 5432
      PGHOST: db
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
volumes:
  pgdata: