version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ameciclo/ideciclo
    docker:
      - image: circleci/buildpack-deps:stretch
workflows:
  build-latest:
    jobs:
      - build_and_test
      - docker-build:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - docker-build
          filters:
            branches:
              only: master
  
jobs:
  build_and_test:
    docker:
      - image: circleci/elixir:1.9
        environment:
          MIX_ENV: test
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_PASSWORD: ideciclo
          POSTGRES_USER: ideciclo
          POSTGRES_DB: ideciclo_test

    working_directory: ~/ideciclo
    steps:  # commands that comprise the `build` job
      - checkout  # check out source code to working directory

      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)

      - restore_cache:  # restores saved mix cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:  # list of cache keys, in decreasing specificity
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile  # get updated dependencies & compile them
      - save_cache:  # generate and store mix cache
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache: # don't forget to save a *build* cache, too
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"

      - run:  # special utility that stalls main process until DB is ready
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: mix test  # run all tests in project

      - store_test_results:  # upload junit test results for display in Test Summary
          # Read more: https://circleci.com/docs/2.0/collect-test-data/
          path: _build/test/lib/ideciclo # Replace with the name of your :app
      - persist_to_workspace:
          root: ~/ideciclo
          paths: 
            - .

  docker-build:
    working_directory: ~/ideciclo
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/ideciclo
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

